version: "2.0"

services:
  front:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - KINTO_URL=/kinto/v1
      - SENTRY_PUBLIC_DSN=https://a681630d02834fddaaf37fbccd62cd5b@sentry.num.social.gouv.fr/23
    ports:
      - 3001:3000
